; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = encoder_read

[env:main]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = lolin32_lite
framework = arduino
build_src_filter = +<main.cpp>

lib_deps =
	askuric/Simple FOC@2.3.5
lib_archive = false

monitor_speed = 115200
upload_port = COM11
monitor_port = COM11

[env:encoder_read]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = lolin32_lite
framework = arduino
build_src_filter = +<encoder_read/main.cpp>

monitor_speed = 115200
upload_port = COM10
monitor_port = COM10